#!/usr/bin/env bash

export CONTECO_LABEL="package.ksqldb_sasl - ModEco"
export CONTECO_DESCRIPTION="The ModEco Confluent ksqlDB package, with SASL authentication."

export CONTECO_TYPE="package"
export CONTECO_NAME="ksqldb_sasl"
export CONTECO_TAG="0.12.0"


export CONTECO_BASE="image.wrapper"
export CONTECO_BUILD="modeco"
