#!/usr/bin/env bash


prefix="package_ksqldb_sasl_$2"

if [[ "package_ksqldb_sasl_ksqldb_sasl_ksql_server_queries_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create package_ksqldb_sasl_ksqldb_sasl_ksql_server_queries_volume
	fi
	
